### ISSUE TITLE
Response isn't resolved when form response event fires.

### ISSUE THREAD

**Issue by hickscorp** [PolymerElements/iron-form#112]
This might be related to #111 and #83.

I basically have a `form is="iron-form"`. It submits data using post, and I'm listening to `iron-form-response` with this function:
```
function(event) {
  console.log(event, event.detail, event.detail.data);
}
```

![Screenie](http://i.imgur.com/BWdk95f.png)

Instead I have to do something like:

```
this.$.form.addEventListener('iron-form-response', function(event) {
  event.detail.completes.then(function(req) {
    console.log(req.response);
  });
});
```

It is counter-intuitive and not mentioned in the docs that there is no guarantee for the underlying promise to not be fulfilled when the form event fires.

Guaranteeing it (Eg waiting for the `iron-request` promise to either fulfill or reject to trigger the form event) would be backward compatible and less of a headache for newcomers.

**Comment by rictic** [comment]
Look at `event.detail.response` instead, as in this example: https://jsbin.com/mijuxocuho/edit?html,output

**Comment by hickscorp** [comment]
@rictic thanks.
