### ISSUE TITLE
Can't submit element nested within paper-dropdown-menu

### ISSUE THREAD

**Issue by cpboyd** [PolymerElements/iron-form#114]
Since https://github.com/PolymerElements/iron-form/commit/05c226c3d726baa9a36490d06cfdbd8a0a8a2a1e I've had issues with nested elements.

I had been nesting a custom element (https://github.com/cpboyd/paper-menu-input) that also implements the iron-form-element-behavior within the paper-dropdown-menu (primarily because I wanted to submit the numeric value rather than the label string).

Since paper-dropdown-menu implements iron-form-element-behavior, the value of the nested element is blocked from the submission.

The paper-dropdown-menu does not have a name attribute set, but my custom paper-menu-input does.

Is there perhaps a way that to modify the newly added check to also verify that the parent iron-form-element has a name attribute set?

**Comment by notwaldorf** [comment]
Ah, I see. Here's a repro step, for future testing: https://jsbin.com/kidelu/15/edit?html

I think what we should do is check whether the parent actually has a `name` attribute (i.e. is included in the form). I'll send a PR to fix this

**Comment by cpboyd** [comment]
@notwaldorf Thanks!
