### ISSUE TITLE
Setting properties in `iron-form-presubmit` event do not get set for request.

### ISSUE THREAD

**Issue by runia1** [PolymerElements/iron-form#115]
What I mean is, if you attach an event listener for `iron-form-presubmit` and in the listener you do something like set headers property, or contentType property on the iron-form, it does not get set on the xhr request before being sent.  Example:

app.$.editProfileForm.addEventListener('iron-form-presubmit', function() {
      console.log('iron-form-presubmit called');
      //modify the request so it conforms to our api standards.
      this.contentType = 'application/json';                                 //setting on iron-form does not work.
      this.request.contentType = 'application/json';                    //setting on request does.
      this.headers = {                                                                  //does not work.
        'Authorization': 'Bearer ' + app.$.userJWT.value
      };
      this.request.headers = {                                                    //does work.
        'Authorization': 'Bearer ' + app.$.userJWT.value
      };
    });

I did some digging and it appears that the iron-form properties get set to the request properties, them the presubmit event is fired after, so if any changes to the iron-form properties are made in the presubmit event, they basically get ignored until the next submit.  Possible solutions would be checking if iron-form property values were changed by presubmit event, or an easier solution would just be to let developers know that they need to use the actual request object => 'this.request'.  Thanks, hope this helps someone.

**Comment by ahedderich** [comment]
Why don't you set these properties after the form is ready or hook it to the normal submit event?
Presubmit was only introduced to handle special cases where you have to manually change the iron-request object like file transfers.

**Comment by notwaldorf** [comment]
Yup, @ahedderich is right. The `presubmit` event is fired after the `iron-ajax` request has been set up, but _right before_ it's actually fired, so that you can modify the parameters sent to the server.

If you want to modify the `contentType` or the `headers`, you should do this inline in HTML (`<form is="iron-form content-type="application/json">`), or before actually firing the request, but definitely not in the `presubmit` event
