### ISSUE TITLE
Shadow DOM: iron-form submit not show native validation

### ISSUE THREAD

**Issue by userquin** [PolymerElements/iron-form#119]
### Description
Using iron-form with shadow DOM doesn't show native validation, while the same code with shady DOM works as expected.

### Expected outcome
Native validation must be rendered

### Actual outcome
Native validation NOT rendered

### Live Demo
http://jsbin.com/joruge/edit?html,output

### Steps to reproduce

1. Left blank `Enter some text` element in the page.
2. Click the `Submit` button.
3. Change 'shadow' to 'shady' and click again `Submit` button.

### Browsers Affected

- [X ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
Yes, that unfortunately is not something we can fix. In the Shadow DOM, the browser does not see the nested inputs, so it can't trigger the native validation UI on them. There's also no imperative way to trigger this native UI (only the browser can, if the browser deems it necessary) ☹️

**Comment by notwaldorf** [comment]
Going to close this, since there's nothing we can do at this point :(
