### ISSUE TITLE
Duplicate reading of custom elements' value

### ISSUE THREAD

**Issue by inureyes** [PolymerElements/iron-form#12]
* Currently, iron-form tries to evade duplicate reading from same form elements using hasAttribute('is'). However, not every native form elements in custom element has "is" attribute. Therefore every routine that uses hasAttribute("is") as flag can be malfunctioning.
 * Examples
   * ```<input is="iron-input"> ``` : has "is" attribute. Fine.
   * ```<textarea>``` in iron-autogrow-textarea : does not have "is" attribute. Therefore the value of ```<paper-textarea``` will be referenced twice. (if it has "name" attribute), and return the array with duplicated values. Please read the code below.

 iron-form 166-181
```
         // Also go through the form's native elements.
         for (var el, i = 0; el = this.elements[i], i < this.elements.length; i++) {
           // Checkboxes and radio buttons should only use their value if they're checked.
           // Also, custom elements that extend native elements (like an
           // `<input is="fancy-input">`) will appear in both lists. Since they
           // were already added as a custom element, they don't need
           // to be re-added.
           if (!el.name || !this._useValue(el) ||
               (el.hasAttribute('is') && json[el.name])) {
             continue;
           }
           addSerializedElement(el);
         }
```
textarea in ```<paper-textarea>``` (part of paper-input) will return false when el.hasAttribute('is') is called. If ```<paper-textarea>``` has name and its type is not radio or checkbox, If statement will be false and ```addSerializedElement``` will call again even it is already called before.

 * Currently affected methods
  * serialize
  * validate
  * Now paper-textarea is not working. However, if someone try to use ```<paper-toggle-button>``` as a part of iron-form, it will not work too.

**Comment by notwaldorf** [comment]
Re: `paper-toggle-button`: I haven't got around to add the `IronFormElementBehavior` to it (nor to checkbox/radio-button), which means the `iron-form` isn't tracking them. I'll get on that asap (and I think `iron-autogrow-textarea` should have the same fix.

The idea is that if the element is a custom element, the first loop should take care of validating it/serializing its behaviour. The requirement, of course, is that the `iron-form` knows about it, and I think at the moment only `paper-input` meets that requirement.

Fixes coming soon!

**Comment by notwaldorf** [comment]
@inureyes Same question as in #41. Everything looks fine with the latest versions of inputs and `iron-form`, I think

**Comment by inureyes** [comment]
@notwaldorf I tested it and everything is working fine now. :+1:
