### ISSUE TITLE
iron-form not submitting form as json despite content type application/json

### ISSUE THREAD

**Issue by RobMaskell** [PolymerElements/iron-form#120]
### Description

Might be my understanding of iron-form and what it is supposed to do, but I'm trying to use it to submit a form to a rest api with a json payload.

the relevant parts of my form template looks like this

```
	<template>
		<form is="iron-form" id="problemForm" method="post" action="http://localhost:8080/api/test" content-type="application/json">
		
			<paper-input name="name" label="name"></paper-input>
			<paper-textarea name="description" label="describe the problem"></paper-textarea>

			<paper-button type="submit" raised onclick="submitForm(event)"><iron-icon icon="save"></iron-icon>Submit</paper-button>
			
		</form>
	</template>

	<script>
  		function submitForm(event) {
			Polymer.dom(event).localTarget.parentElement.submit();
		}
	</script>
```

I have also tried contentType as the attribute.

### Expected outcome

request body containing serialized json of my form

### Actual outcome

request body containing url encoded version of my form

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by RobMaskell** [comment]
Fixed it, documenting here for any others new to Polymer. I'm using the starter kit which has quite old versions of the element collections listed in bower.json so I updated to

```
{
  "name": "polymer-starter-kit",
  "private": true,
  "dependencies": {
    "iron-elements": "PolymerElements/iron-elements#^1.0.9",
    "neon-elements": "PolymerElements/neon-elements#^1.0.0",
    "page": "visionmedia/page.js#~1.6.4",
    "paper-elements": "PolymerElements/paper-elements#^1.0.7",
    "platinum-elements": "PolymerElements/platinum-elements#^2.0.0",
    "polymer": "Polymer/polymer#^1.4.0"
  },
  "devDependencies": {
    "web-component-tester": "^4.0.0"
  },
  "ignore": []
}
```

and also I'd forgotten to add iron-form import to my element which failed silently.

**Comment by notwaldorf** [comment]
Sweet, glad you sorted it out!

**Comment by philipjmurphy** [comment]
Also, don't forget to run (doh!)

`bower install --save PolymerElements/iron-form
`

and include

`<link rel="import" href="../bower_components/iron-form/iron-form.html">
`

Also, I needed to specify: content-type="application/json", and not the contentType attribute as it doesn't appear to work.
