### ISSUE TITLE
still problems with form.reset()

### ISSUE THREAD

**Issue by atomikolex** [PolymerElements/iron-form#126]
### Description
Resetting an iron-form with the reset()-method.

### Expected outcome
Form elements get populated with label text again.

### Actual outcome
Reset is working as expected for paper-input and gold-email-input elements. Paper-textarea elements however get populated with the label text AND 'undefined', scrambling up the displayed text.

### Setup
Instead of submit I am just pushing to a Firebase with
`  submitHandler: function(event) {
      var firebaseRef = new Firebase(firebase);
      firebaseRef.push(this.$.contact.serialize());
      this.$.contact.reset();
      event.preventDefault();
  }`

**Comment by dman777** [comment]
:+1:  I have the same issue `paper-textarea` and form reset, leaving `undefined` in the text area.  I am not using Firebase.

**Comment by notwaldorf** [comment]
Yup, that looks like a bug. Here's a repro jsbin: http://jsbin.com/biyime/edit?html,output.

It seems that this is a bug in `paper-textarea` - doing `someArea.value = 'foo';` does not update the containing `iron-autogrow-textarea`.

**Comment by notwaldorf** [comment]
(If anyone wants to fix it, a PR would be greatly appreciated! 🍰 )

**Comment by tony19** [comment]
It turns out the native `<input>`/`<textarea>` display literal "undefined" when its value is set to `undefined`. Weird.

**Comment by tony19** [comment]
@notwaldorf PR #144 sent your way
