### ISSUE TITLE
`iron-form` ignores elements with `prevent-invalid-input`

### ISSUE THREAD

**Issue by patgmiller** [PolymerElements/iron-form#127]
### Description

The `iron-form` element does not validate elements with `prevent-invalid-input` set. 

```html
<form is="iron-form" id="form" method="post" action="https://httpbin.org/post">
    <gold-email-input name="email" label="Email" auto-validate  prevent-invalid-input></gold-email-input>
    <gold-phone-input name="phone" label="Phone" auto-validate prevent-invalid-input></gold-phone-input>
    <paper-input name="regex" label="Slug RegEx" auto-validate prevent-invalid-input pattern="^[\w-]+$" error-message="Only letters and dashes are allowed."></paper-input>
    <paper-button raised >Submit</paper-button>
  </form>
```

### Expected outcome

The form should validate elements which have `prevent-invalid-input` set.

### Actual outcome

The form instead submits invalid input. 

### Live Demo

[http://jsbin.com/nodeno/8/edit?html,output](http://jsbin.com/nodeno/8/edit?html,output)

### Steps to reproduce

1. Open the [demo](http://jsbin.com/nodeno/8/edit?html,output) on jsBin.
2. Enter some invalid data for one the Email, Phone, or RegEx fields.
3. Click the Submit button.
4. Confirm that your input shows as invalid for the input element, but the `form.validate()` returns true in the output.

![screenshot from 2016-05-25 11-01-47](https://cloud.githubusercontent.com/assets/3914379/15549082/2f1ee988-2268-11e6-9f2b-bd4ba1056d70.png)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by patgmiller** [comment]
I'll have a pull request with test in a little bit.

**Comment by notwaldorf** [comment]
I think this is working as intended: you need to add `required` on the elements, so that the form will only submit if they are valid: http://jsbin.com/rerise/edit?html,output.

`prevent-invalid-input` is an attribute of `paper-input` -- the form doesn't care about that; it only looks at elements that are required, and checks their validity (which for paper elements is returned by the `validate` method).

**Comment by patgmiller** [comment]
@notwaldorf, yes technically `prevent-invalid-input` is an attribute of `paper-input`, but the purpose of `iron-form` is 

```
<iron-form>` is an HTML `<form>` element that can validate and submit any custom
elements that implement `Polymer.IronFormElementBehavior`, as well as any
native HTML elements.
```
So saying that `iron-form` doesn't care about that conflicts with the form element description. Aren't, both `iron-form` and `paper-input` developed by the Polymer Elements team, then shouldn't team members be interested in the success of the team as a whole? 

The `iron-from` element should care that it is allowing non-required input to be submitted when it is actually invalid. This is also a type of functionality that commonly included with with many other form validation libraries / utilities. Even though an input is optional, it should be valid if validation is provided.

Secondly there are also other pull requests to `iron-form` which recommend a similar kind of functionality: #43, #95, #123 from you user base, so I am not the only one suggesting this kind of change. Will you please reconsider your decision. 

Sincerely, `patgmiller`

**Comment by patgmiller** [comment]
This quote is taken from the Mozilla Web Developer Guides:

```
Validation constraints on <input> elements

All <input> elements can be validated using the pattern attribute. This attribute expects a case sensitive Regular Expression as its value. If the element's value is not empty and doesn't match the regular expression specified by the pattern attribute, the element is considered invalid.
```

So if we just base the custom validation checks on existence of `pattern` attribute would that be more acceptable to you?

**Comment by chandrasekharh** [comment]
I think this is a very valid request. Adding 'required' attribute to force form to validate may not be feasible all the time. Validating a "non required" field only when it is non-empty is a common scenario. And since iron-form implements custom validate functionality, I hope this is not too hard to achieve. Please reconsider.

**Comment by mvolkmann** [comment]
Yes, please reconsider this. Just because an input is optional (not required), that doesn't mean I don't want to validate it if the user enters a value.

**Comment by sankarbalu1** [comment]
I have the same requirement which @patgmiller has mentioned.Please reconsider this.
