### ISSUE TITLE
elements 'change' event to fire on-change instead on lost-focus

### ISSUE THREAD

**Issue by Mathter2** [PolymerElements/iron-form#129]
### Description
The 'change' event associated with iron-form and other iron-input elements (such as paper-textarea) do no fire the event unless the input looses focus (or at least that's what happens on the demo)

### Expected outcome
To fire the event when the content changes (via keypresses or other events)

### Actual outcome
Fires after loosing focus

### Live Demo
https://elements.polymer-project.org/elements/iron-form?view=demo:demo/index.html&active=iron-form

Specific to the sample titled: Example of an iron-form reacting to state changes.

### Steps to reproduce
Go to the iron-form element demo and look for Example of an iron-form reacting to state changes.
Check the checkbox.
Type a password.
Type a name.

Submit button wont be enabled until the name inout box looses focus.
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10
### Notes
Hi. Maybe this is not a bug, but an enhancement or perhaps the demo could use some other event that works better for it's intended purpose.

It would be great to have a change event that fires every time the data in the input changes, or the demo to use another already-created event so the submit button becomes available.

I thought on using a key-press event, but not sure if this would work on mobile.

Thank you.

**Comment by notwaldorf** [comment]
That is not what the native `change` event does, for inputs: https://developer.mozilla.org/en-US/docs/Web/Events/change. It is fired when the value is _committed_, not just updated, and that happens when you press 'enter'. or the input loses focus.

Here's a demo of the native inputs doing the same thing: http://jsbin.com/sicoda/edit?html,console,output
