### ISSUE TITLE
this.submit() in FF calls native form function

### ISSUE THREAD

**Issue by mcarey1590** [PolymerElements/iron-form#13]
When testing iron-form using Firefox, the ```this.submit()``` of the iron-form element is never getting called. Instead, it it is calling the native submit function causing a page refresh.

Confirmed this by changing the name of the submit function to see it work as expected

**Comment by notwaldorf** [comment]
I'm not sure I can reproduce this. In FF, if I press the "native submit" button, it calls the native form submit, which is intercepted by the `iron-form's` `submit` listener, which hits the `_onSubmit()` method, and calls `this.submit()` fine. 

The `paper-button` just calls the `submit()` method directly.

Can you checkout the latest version and try again, please?

**Comment by notwaldorf** [comment]
I'm closing this since it's been inactive and I'm fairly sure it's been fixed. Please re-open it if it happens again! :zap:
