### ISSUE TITLE
PUT requests should submit content in the body instead of as query parameters

### ISSUE THREAD

**Issue by dhaber** [PolymerElements/iron-form#130]
### Description
A PUT request is similar to a POST in that the content goes in the body and not in query parameters.

### Expected outcome
If the method is set as "PUT" the content should go in the body and not be added as query parameters.

### Actual outcome
Content is added query params

### Live Demo
http://jsbin.com/qurunayivo/edit?html,output

### Steps to reproduce
1. Make a form with method "put"
2. Submit form
3. Note that AJAX request adds content as query parameters instead of body content

### Browsers Affected
- [x ] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by notwaldorf** [comment]
`iron-form` is a type extension of the native `form` element, and 'PUT' is not a method supported by forms: https://www.w3.org/TR/html5/forms.html#form-submission. The only accepted methods are `get` and `post`.
