### ISSUE TITLE
feature request: populate() to set input values from Object

### ISSUE THREAD

**Issue by Schibum** [PolymerElements/iron-form#132]
An inverse function for serialize() to pre-populate the from with values (as returned from serialize()) would be nice to have.
This could be useful when editing existing data, that has already been persisted before.

**Comment by notwaldorf** [comment]
Populating the form with values means going through each of the elements in the form (which are in your control), and you setting their value. Since all of these could be arbitrary controls (that maybe don't even have a straight-forward settable value), I don't think the form should control this -- it sounds like a bad inversion of control for this case :(

**Comment by slawomir-brzezinski-at-interxion** [comment]
Hi. Just stumbled upon this while also looking for a similar feature.  Looks like #147 is also a dupe, so, I don't know... If there's a `serialize`, maybe `deserialize` is really a natural thing to have. Similar things were coveted and created for jQuery in the old school too ([stackoverflow](http://stackoverflow.com/q/6992585/4356868)).

Re:
> Populating the form with values means going through each of the elements in the form (which are in your control), and you setting their value.

It looks like `serialize` [does exactly that](https://github.com/PolymerElements/iron-form/blob/4517c781c6fea2d353b703c33bf93e9c5e194c71/iron-form.html#L306). Would it not make sense to apply exactly the same traversal, just this time using the `value` as setters? I know there's extra complexity to getting to the object's value by path, but perhaps worth supporting at least the simplest flat cases?  
Alternatively, how about rather going through all properties of the object and looking for elements with the matching `name`?

The dupe did make me aware of that solution of using two-way binding, but it sounds like you then either need to repeat yourself (put property names both into value bindings (`value={{propName}}`) as well as input's `name=propName`), or do away with the built-in submit altogether, and just back the form elements with a javascript object that you send on submit. But then... this leave much of the iron-form functionality unused.

Anyways, Just wondering if I'm getting it all wrong. Thanks for your work!
