### ISSUE TITLE
Can't access defined functions from the iron-form-response

### ISSUE THREAD

**Issue by milesje** [PolymerElements/iron-form#133]
### Description
When receiving the iron-form-response event I am unable to access other functions defined in my element.

### Expected outcome
I should be able to access all functions and properties of the element that contains the iron-form.

### Actual outcome
receive an exception: Uncaught TypeError: this.isTokenExpired is not a function

### Code
```
isTokenExpired: function(){
     consoel.log('isTokenExpired);
},
formResponse: function (event){
      console.log('Form Response')
      this.isTokenExpired();
},
ready: function() {
        // `ready` is called after all elements have been configured, but
        // propagates bottom-up. This element's children are ready, but parents
        // are not.
        //
        // This is the point where you should make modifications to the DOM (when
        // necessary), or kick off any processes the element wants to perform.
        this.isTokenExpired();
        this.$.form.addEventListener('iron-form-response', this.formResponse);
        this.$.form.addEventListener('iron-form-presubmit', this.formPresubmit);
        this.$.form.addEventListener('iron-form-submit', this.formSubmit);
        this.$.form.addEventListener('iron-form-error', this.formError);
},
```

**Comment by milesje** [comment]
Also unable to access HTML elements using "document.getElementById('idName').reset()! This will cause an error in the console. Which is the same error I get when calling this.$.idName.reset().
Uncaught TypeError: Cannot read property 'reset' of null

**Comment by milesje** [comment]
If I setup the event listeners using
listeners: ['iron-form-response', 'formResponse',...]
I am able to access internal function, but if setting up the event listeners as shown above I am not able to access them.

**Comment by notwaldorf** [comment]
Closing, as this is a problem with how the listener is set up: you need to bind it to the `this` reference: 
`this.$.form.addEventListener('iron-form-response', this.formResponse.bind(this))`

See http://jsbin.com/gohiluw/edit?html,console,output for a working example.
