### ISSUE TITLE
paper-checkbox JSON value

### ISSUE THREAD

**Issue by milesje** [PolymerElements/iron-form#134]
### Description
With contentType set to "application/json" a paper-checkbox will have is value set to either "on" or NULL.

### Expected outcome
I would expect a checkbox to be set to a Boolean value of true or false.

**Comment by notwaldorf** [comment]
Even though this might look weird, it's working as intended. This is meant to mirror the behaviour of the native checkbox, which sets the value to "on" when checked: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

**Comment by milesje** [comment]
Thanks for the clarification.
