### ISSUE TITLE
Validation on paper-input-container

### ISSUE THREAD

**Issue by pongsakornv** [PolymerElements/iron-form#136]
if I have code like this

```
<form is="tron-form" id='thisForm'>

<paper-input name='inputA'></paper-input>

<paper-input-container name='inputB'>
  <label>B Label</label>
  <b-input name='inputB' class="paper-input-input"></b-input>
  <paper-input-error>Error of B</paper-input-error>
</paper-input-container>

</form>
```

then i use thisForm.serialize() to get list of key-pair value within this form,

I got only inputA element. 

InputB based on 

https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-input 

on the last example.

Did I do something wrong or this should be considered as a bug?

**Comment by notwaldorf** [comment]
Ah, I think there's a problem with your `<b-input>` bit. Here's a working example that's using an `iron-input` instead: http://jsbin.com/xapafug/edit?html,console,output

Basically, `iron-form` assumes that its children have a `value` attribute. `paper-input-container` knows how to get that from an `iron-input`'s `bindValue` attribute -- but if your custom element `b-input` doesn't expose that correctly, then it doesn't work.

Hope this helps! Closing this for now, as it seems like it's a bug with the sample code, but let me know if you have a reproducible jsbin with your problem

**Comment by JunedS** [comment]
First of all the bug says about validation on paper-input-container and then we are speaking about serialize its misleading isn't it!
@notwaldorf  Say in your same example if we set required on input with is="iron-input" as required and if we invoke validate() on form why does it return true?
