### ISSUE TITLE
iron-form should skip elements which have a registered parent

### ISSUE THREAD

**Issue by fejesjoco** [PolymerElements/iron-form#142]
Imagine that I create an advanced input control that has a single value, but it consists of other input controls. Eg. I create an element where the user can type into a paper-input or select from a paper-dropdown-menu. I only want to validate the value of my composite input control, but not its children (they may have validation rules but I still want to deal with that manually in my own validate() function). However, these children have IronFormElementBehavior, so they register themselves invariably.

iron-form already handles this correctly in the serialize() function (calls _isChildOfRegisteredParent). The same should be done for validate().

**Comment by notwaldorf** [comment]
Oh, yeah, I think that makes sense

**Comment by fejesjoco** [comment]
Can I send a PR? This seems easy enough to do.

**Comment by notwaldorf** [comment]
@fejesjoco Absolutely, please!
