### ISSUE TITLE
Load object/json into form fields?

### ISSUE THREAD

**Issue by dannyphung** [PolymerElements/iron-form#147]
Hi team,
I need to load an js object into iron-form fields, but can't make two-way binding to work. So anyone here ever do that before or are there any work around?

**Comment by notwaldorf** [comment]
Do you have an example of what you're doing? A JSBin with repro steps would help.

What kind of form fields? (you can literally put anything in an `iron-form`, so that doesn't really say anything)

**Comment by dannyphung** [comment]
I solved this problem. Just about implement two-way binding into every form field. It works now. Thank you for your time.
