### ISSUE TITLE
Pressing Enter Will Not Submit Forms with More than 1 Input

### ISSUE THREAD

**Issue by tzyhhaur** [PolymerElements/iron-form#150]
Taking the demo code at https://elements.polymer-project.org/elements/iron-form?view=demo:demo/index.html&active=iron-form as example. The following code works well when I press enter on the input.
```html
<form is="iron-form" method="get" action="/" id="presubmit">
  <paper-input name="name" label="Name" value="Batman" required></paper-input>
  <paper-button raised onclick="_submit(event)">Submit</paper-button>
  <paper-button raised onclick="_reset(event)">Reset</paper-button>
  <div class="output"></div>
</form>
<script>
  function _submit(event) {
    Polymer.dom(event).localTarget.parentElement.submit();
  }
  function _reset(event) {
    var form = Polymer.dom(event).localTarget.parentElement
    form.reset();
    form.querySelector('.output').innerHTML = '';
  }
  presubmit.addEventListener('iron-form-presubmit', function(event) {
    this.request.params['sidekick'] = 'Robin';
  });
  presubmit.addEventListener('iron-form-submit', function(event) {
    this.querySelector('.output').innerHTML = JSON.stringify(event.detail);
  });
</script>
```

However, suppose I add another paper-input DOM, as followed, pressing enter key (on either input) would not trigger the iron-form-submit event anymore. Tested this on Safari and Chrome.

```html
<form is="iron-form" method="get" action="/" id="presubmit">
  <paper-input></paper-input>
  <paper-input name="name" label="Name" value="Batman" required></paper-input>
  <paper-button raised onclick="_submit(event)">Submit</paper-button>
  <paper-button raised onclick="_reset(event)">Reset</paper-button>
  <div class="output"></div>
</form>
```

**Comment by cgriffin4** [comment]
To make your example work you'll need to have a button with the type of submit in the form. The submit on enter behavior is native form behavior for the browser and is only triggered if there is a submit button. The visibility of the button is not considered so an acceptable "workaround" is to include a hidden submit button. I'd have to look at the demo more closely to see why it DOES work. 

Further information can be found in issue #32 

As a side note. Worrisome you haven't received a response to this earlier.

**Comment by notwaldorf** [comment]
@cgriffin4 This seems to be the native form behaviour: http://jsbin.com/niyuko/edit?html,output
If you have exactly one input inside a form, whether or not there's an `<input type="submit">`, the form will be submitted. If you add a second input, then the presence of the `<input type="submit">` is mandatory.

Closing, as @cgriffin4's answer is correct
