### ISSUE TITLE
Iron-Form Reset with Paper Menu Not Displaying Selection

### ISSUE THREAD

**Issue by jklaw90** [PolymerElements/iron-form#159]
### Description

iron-form reset form is not truly clearing out paper menu selection, as a result it is not displaying correctly.

### Expected outcome

After resetting form you should allow the user to select **any** of the paper menu selections.

### Actual outcome

After resetting form you are unable to select the selection you selected previously.

### Live Demo
https://elements.polymer-project.org/elements/iron-form?view=demo:demo/index.html&active=iron-form

### Steps to reproduce

```
1. Open live demo in chrome.
2. Navigate to the first demo with "name" "I like donuts" etc...
3. Select "Volvo" form the Cars drop down menu
4. Click reset.
5. Try to select "Volvo" from the cars drop down menu again.
6. View the selection, it still lists "Cars" didn't update to "Saab".
```
### Browsers Affected
- [x ] Chrome
- [x ] Firefox
- [ x] Safari 9
- [x ] Safari 8
- [x ] Safari 7
- [x ] Edge
- [x ] IE 11
- [x ] IE 10

**Comment by kaseyhinton** [comment]
* I am having this same issue still. Any fixes??
