### ISSUE TITLE
The `checkValidity()` function always returns true when shadow DOM is enabled

### ISSUE THREAD

**Issue by jarrodek** [PolymerElements/iron-form#160]
### Description
The `checkValidity()` function called on the `iron-form` element always returns `true` if the shadow DOM is enabled.

According to the [Forms in HTML](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms_in_HTML#Constraint_Validation_API) article:
> On HTMLFormElement objects, the checkValidity() method, which returns true if all of this form element's associated elements that are subject to constraint validation satisfy their constraints, and false if any do not.

When shady DOM is used then this is true. The function returns `false` if the form elements are invalid. As soon as I switch to the shadow DOM it always returns `true`.

### Expected outcome
The `checkValidity()` function called on `iron-form` when shadow DOM is used returns `false` if the form elements did not pass the validation.

### Actual outcome
The function always returns true whether form elements are valid or not.

### Live Demo
https://jsbin.com/vokeko/edit?html,js,output

### Steps to reproduce
1. Set `Polymer.dom` global setting to `shadow`
2. Add `iron-form` and `paper-input` elements to the page
3. Set the `required` and `auto-validate` properties on `paper-input`
4. Call the `checkValidity()` function of the form.

### Browsers Affected
- [x] Chrome
- [ ] Firefox  
- [ ] Safari 9 - can't test it 
- [ ] Safari 8 - can't test it
- [ ] Safari 7 - can't test it
- [ ] Edge - can't test it
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
By default, a native form only tracks `input` elements, and doesn't look at custom elements. `checkValidity` hasn't been patched to work with custom elements, instead a new method, `validate`, exists to do that. I've updated your jsbin to show this works: https://jsbin.com/sojesef/edit?html,js,output

Closing, as `checkValidity` isn't supposed to work this way :(
