### ISSUE TITLE
iron-form element does not serialise all duplicates if the first one has value equal to empty string

### ISSUE THREAD

**Issue by tmpduarte** [PolymerElements/iron-form#162]
The `iron-form` element does not serialise all duplicates if the first one has value equal to empty string

## Expected outcome

All values are serialised, even if they are empty strings.

## Actual outcome

Not all duplicate input element values are serialised if the first one is an empty string.

## Steps to reproduce

`
<template>

      <form is="iron-form">

        <input name="foo" value="bar">

        <input name="foo" value="barbar">

        <input name="empty" value="">

        <input name="empty" value="">

      </form>

    </template>
`

When this form is submitted the serialised object should be:
`{ 
foo: ["bar", "barbar"],
empty: ["", ""]
}`

In reality it is:

`{ 
foo: ["bar", "barbar"],
empty: ""
}`

**Comment by notwaldorf** [comment]
This looks fixed in the 2.0 element. I've added a test for this in ab9b850
