### ISSUE TITLE
form.ajax.contenType should be taken from _form.enctype

### ISSUE THREAD

**Issue by jehna** [PolymerElements/iron-form#167]
### Version affected

[2.0-preview](https://github.com/PolymerElements/iron-form/tree/2.0-preview)

### Description

`iron-form` doesn't handle the MIME type of form correctly

### Expected outcome

`iron-form` should take the `iron-ajax`'s contentType from the form's `enctype` attribute

### Actual outcome

`iron-form` [sets the request's `contentType` to the nonexisting `HTMLForm.contentType`](https://github.com/PolymerElements/iron-form/blob/2.0-preview/iron-form.html#L274)

### Live Demo

http://jsbin.com/ranacirupe/3/edit?html,console,output

### Steps to reproduce

1. Create a Polymer component
2. Add form with enctype `<form enctype="application/x-www-form-urlencoded"></form>`
3. Wrap the form with `iron-form` component
4. Submit the form
4. The `iron-ajax` component's contentType is `undefined`

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
This has been fixed!
