### ISSUE TITLE
ContentType has no effect in 2.0-preview

### ISSUE THREAD

**Issue by hubjac1** [PolymerElements/iron-form#169]
### Description

The attribute contentType is not taken into account on post.

Example:

      <iron-form id="myForm">
        <form method="post" action="/a/valid/url" content-type="application/json">
          <paper-input id="foo" label="Foo" name="foo" value="fooValue"></paper-input>
          <paper-input id="bar" label="bar" name="bar" value="barValue"></paper-input>

          <paper-button id="mybutton" raised>Action</paper-button>
          <input type="submit" hidden>
        </form>
      </iron-form>

### Expected outcome

The code above is expected to post an Json '{"foo":"fooValue","bar":"barValue"}' with the reques-headers content-type set to "application/json". 

### Actual outcome

But we got `Content-Type:text/plain;charset=UTF-8`

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
Fixed in 	eadaddd
