### ISSUE TITLE
Polymer 2.0 withCredentials and contentType configuration issue

### ISSUE THREAD

**Issue by H3dz** [PolymerElements/iron-form#173]
### Description
In the iron-form 2.0 preview, withCredentials is commented out and can only be set using a pre submit hook.

### Steps to reproduce
```
<iron-form
          id="form"
          with-credentials
          on-iron-form-presubmit="onPreSubmit"
          on-iron-form-submit="onSubmit"
          on-iron-form-response="onResponse">
  <form method="post" action="sign-in">
  </form>
</iron-form>
```

**Comment by hubjac1** [comment]
Hi H3dz,

I have a pull request pending with this fix. 
See https://github.com/PolymerElements/iron-form/issues/170

**Comment by H3dz** [comment]
Hi @hubjac1, I updated the issue since part of it was a duplicate.

**Comment by H3dz** [comment]
Commit 2c26f77829ebebf4e35f77915e233ba7df6b3316 fixed this issue.
