### ISSUE TITLE
Iron form serialize method always returning undefined on Polymer 2.0

### ISSUE THREAD

**Issue by schmeisk** [PolymerElements/iron-form#174]
### Description
When submit serialize method returns undefined, and the submit function it's called two times;

### Expected outcome

`{cenas: input}`

### Actual outcome
`undefined`
### Live Demo
https://jsbin.com/micinalacu/1/edit?html,console,output

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

I did not test in another browser.
Stackoverflow question:
http://stackoverflow.com/questions/43075125/iron-form-with-polymer-2-0

**Comment by notwaldorf** [comment]
There's no method called `serialize` on `iron-form#2.0-preview` right now; it's called `serializeForm`. There was a bug where Polymer had a `serialize` method, and that was stomping over the form's.

**Comment by schmeisk** [comment]
@notwaldorf yah, with the serializeForm works. But why it's called two times? and why I did not receive a run time error trying to execute a non defined method?
