### ISSUE TITLE
Bug on line 242 of iron-form.html (master branch)

### ISSUE THREAD

**Issue by sweatybridge** [PolymerElements/iron-form#184]
### Description

https://github.com/PolymerElements/iron-form/blob/master/iron-form.html#L242
`this.method` is undefined. It should be `this.request.method` instead.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by sweatybridge** [comment]
@notwaldorf can we get this fixed asap? It's causing broken builds on master.

**Comment by notwaldorf** [comment]
Huh, weird that it hasn't come up before. `this.method` should be the `method` property of the native form (equivalent to `this.getAttribute('method');`). By any chance in your app you have an input with `name=method`?

**Comment by notwaldorf** [comment]
Sending a PR to fix it now, i'm just curious why the sudden problem

**Comment by sweatybridge** [comment]
Yup, that's exactly what I have :) a corner case indeed.

**Comment by notwaldorf** [comment]
Ah, sweet, that makes total sense!
