### ISSUE TITLE
No v2.0.0 release.

### ISSUE THREAD

**Issue by manolo** [PolymerElements/iron-form#187]
It seems all iron elements has a 2.0.0 release, but iron-form doesn't, so we have to depend on preview. 
Is that intentional, or you is someone working on it.

**Comment by notwaldorf** [comment]
The `2.0-preview` is not complete, which is why it hasn't been merged to master, and it hasn't been included in the list of elements that are 2.0 ready.
I will be working on it once I/O is over

**Comment by philkunz** [comment]
any ETA here? :) Thanks for the awesome work btw.

**Comment by esd100** [comment]
Any ETA? Could use a final version for mid year deadlines

**Comment by notwaldorf** [comment]
Trying to have it done by the end of the week

**Comment by peterlauri** [comment]
If we are 2 month away from our own production release, should we feel safe to use 2.0-preview for now? Is it close to feature complete?

**Comment by notwaldorf** [comment]
@peterlauri Going to release it today or tomorrow, so I'd say it's feature complete!

**Comment by notwaldorf** [comment]
Donzo! 🎉🎉 🎉
