### ISSUE TITLE
firebase?

### ISSUE THREAD

**Issue by TimWillis** [PolymerElements/iron-form#19]
I would like to use this with firebase, but it's tied directly with iron-ajax, I am not using the rest api with firebase. It would be nice to have more control over the form action...

**Comment by notwaldorf** [comment]
I am working on a PR that will be exposing the `iron-ajax` as a public property, so you will be able to override that then. Would that work for you?

**Comment by TimWillis** [comment]
Yes, I think that is what I needed.

Thanks
Tim

On Mon, Oct 19, 2015 at 3:27 PM, Monica Dinculescu <notifications@github.com
