### ISSUE TITLE
iron-form not working in polymer 2

### ISSUE THREAD

**Issue by esd100** [PolymerElements/iron-form#190]
None of the elements within my form are displaying.

**Comment by TomK** [comment]
Please follow the guidelines for issue submissions. Nobody will be able to help you if you don't provide any details.

**Comment by esd100** [comment]
@TomK 

Well, honestly, there isn't much more to say. The title says everything.

None of the elements within my form are displaying after trying to migrate to Polymer 2.

All of the elements within my form were displaying and functioning properly before trying to migrate to Polymer 2.

What else do you want to know.

**Comment by web-padawan** [comment]
`iron-form` 2.0 is not released, which version are you using?

**Comment by TomK** [comment]
@esd100 an example in jsbin or codepen would be a good start. Maybe some output of your console.

*Just follow the instructions on the New Ticket.*

As @web-padawan said, iron-form is still being worked on to get it to 2.0, but it's working for me with a few tweaks.

**Comment by esd100** [comment]
I'm using the `    "iron-form": "PolymerElements/iron-form#2.0-preview",`

There are no console errors. Just nothing is being displayed. I changed nothing from my 1.0 implementation which was working fine.

**Comment by notwaldorf** [comment]
Please read the `readme` for the 2.0-preview branch -- a lot _has_ in fact changed since 1.0. In 2.0, `iron-form` can no longer be a type extension of the native `form` element, and you need to distribute a `form` to it.

Instructions on how you need to update your code are there: https://github.com/PolymerElements/iron-form/blob/2.0-preview/README.md

**Comment by esd100** [comment]
Still not working.

```
<paper-card>
      <app-toolbar main-title>Log Form</app-toolbar>
      <iron-form>
        <form id="form" method="POST" content-type="application/json" class="layout flex wrap center around-justified">
            <vaadin-date-picker name="Date" label="Pick a date" required></vaadin-date-picker>
            <paper-input name="Minutes" label="Number of Minutes" type="Number" step="15" min="0" required auto-validate></paper-input>
            <nml-categories name="Category" category="{{selectedCategory}}" required></nml-categories>
            <nml-topics name="Topic" selected-category="[[selectedCategory]]" topic="{{selectedTopic}}" required></nml-topics>
            <nml-location name="Location" location="{{selectedLocation}}" required></nml-location>
            <div class="layout nowrap horizontal around-justified">
              <paper-button id="Submit" raised on-tap="submitAction">Submit</paper-button>
              <paper-button id="Reset" raised on-tap="resetAction">Reset</paper-button>
            </div>
        </form>
      </iron-form>
    </paper-card>
```

The only thing that shows up is the paper-buttons at the bottom.

None of the inner elements show up. Not even the paper-input.

**Comment by esd100** [comment]
Got the elements to show up now by double checking all of the elements I was importing. Apparently one missing import for a 2.0 version element makes none of them work.

Even though they show up now, they aren't working properly. Something with animation has gone wrong...
