### ISSUE TITLE
How to add pre-submit event listener in 2.0-preview

### ISSUE THREAD

**Issue by esd100** [PolymerElements/iron-form#192]
The demo doesn't make it clear how to use event listeners in an actual polymer 2 element.  All of the examples given are within html script tags but not similar to what you would see in a typical polymer element.

Could you please give an example of how you would use the pre-submit as exemplified in the readme, 

```
  form.addEventListener('iron-form-presubmit', function() {
      this.request.method = 'put';
      this.request.params['extraParam'] = 'someValue';
    });
```

but within a polymer class, e.g.
```
    class MyApp extends Polymer.Element {
      static get is() {
        return "my-app";
      }
    }

    window.customElements.define(MyApp.is, MyApp);
```

because if I just paste the above example into my class definition, I get an error that says 
`parsing error: Unexpected token . (Fatal)`

I imagine this is something really simple but since I'm a doctor and not a programmer, it's not clear to me what to do. I think a better example in the demo would be really helpful.

**Comment by drdreo** [comment]
I can't figure that out aswell.
I define the listeners in the `<script>`

Using only the id to add, results in an error: 
`
 form.addEventListener
`
>ReferenceError:  form not defined



Waiting for the Imports doesn't work aswell: 
`
 

       HTMLImports.whenReady(function () {
            form.addEventListener('change', function (event) {
              
            });
`

Any progress?

**Comment by drdreo** [comment]
solution to register the EventListener was: - but now the .validate() makes problems, because that ain't a function.
`
connectedCallback() {
                super.connectedCallback();

                let eventsDemo = this.shadowRoot.getElementById('eventsDemo');
                let eventsDemoSubmit = this.shadowRoot.getElementById('eventsDemoSubmit');

                eventsDemo.addEventListener('iron-form-submit', function (event) {
                    console.log("iron form submit");
                    let spinner = this.shadowRoot.getElementById('spinner');

                    spinner.active = false;
                    spinner.hidden = true;
                    eventsDemoSubmit.disabled = false;
                    this.querySelector('.output').innerHTML = JSON.stringify(event.detail);
                });

                eventsDemo.addEventListener('change', function (event) {
                    console.log("form changed");
                    console.log(event);
                    // Validate the entire form to see if we should enable the `Submit` button.
                    eventsDemoSubmit.disabled = !eventsDemo.validate();
                });
            }
`

**Comment by notwaldorf** [comment]
@drdeo You opened https://github.com/PolymerElements/iron-form/issues/196 for the `validate` issue, and as answered there, you need to make sure you're calling `validate` on the `iron-form`, not the nested `form`.

For the original question, here is how I would do it. My guess is that in your original code you didn't really use the right `form` element. I can't really tell, since you didn't post any code snippets to look at :)

```html
<dom-module id="my-app">
    <template>
      <iron-form id="myForm">
        <form action="/foo" method="get">
          <paper-input type="text" name="name" required label="Name" value="Batman"></paper-input>
          <input name="foo" required value="Robin">
          <paper-button raised on-click="_do">Submit</paper-button>
        </form>
      </iron-form>
    </template>
    <script>
      class MyApp extends Polymer.Element {
        static get is() {
          return "my-app";
        }
        constructor() {
          super();
          this._submitted = false;
          this._presubmitted = false;
        }
        ready() {
          super.ready();

          this.$.myForm.addEventListener('iron-form-submit', function() {
            this._submitted = true;
          }.bind(this));

          this.$.myForm.addEventListener('iron-form-presubmit', function() {
            this._presubmitted = true;
          }.bind(this));

          this.$.myForm.addEventListener('iron-form-response', function() {
            console.log(this._submitted);
            console.log(this._presubmitted);
          }.bind(this));
        }
        _do() {
          this.$.myForm.submit();
        }
      }
      window.addEventListener('WebComponentsReady', function() {
        window.customElements.define(MyApp.is, MyApp);
      });
    </script>
  </dom-module>
```

Hope this helps!

**Comment by esd100** [comment]
Thanks @notwaldorf, that example helps. I think you should add something like that to the demo. It's not exactly clear how to do all of the presubmit things with the new polymer 2. 

On another note, I'm having hell of a time with paper-dropdown-menu within my form and nobody is helping.
