### ISSUE TITLE
iron form 2.0-preview demo is not working

### ISSUE THREAD

**Issue by esd100** [PolymerElements/iron-form#193]
@notwaldorf  
Loading iron form 2.0 preview demo from http://127.0.0.1:8081/bower_components/iron-form/demo/index.html is not working.

Can't think of why the packaged demo should not work but it doesn't.

**Comment by notwaldorf** [comment]
If you're using `polymer serve`, the correct path is `http://127.0.0.1:8081/components/iron-form/index.html`. Not sure what your setup is. but here's proof mine runs:
![screen shot 2017-06-19 at 12 04 01](https://user-images.githubusercontent.com/1369170/27301233-5c784f2a-54e7-11e7-88f8-aa16bce5b146.png)

Make sure that you're going to the correct path as given by `polymer serve`. Closing, as I can't repro and there's no errors that I can look into

**Comment by esd100** [comment]
Still not working.

going to that path (http://127.0.0.1:8081/components/iron-form/index.html).
<img width="1440" alt="screen shot 2017-06-24 at 4 18 10 pm" src="https://user-images.githubusercontent.com/4109522/27511697-ca55e40c-58f8-11e7-8acd-e8fe1619f256.png">

clicking on demo in top right corner...
<img width="1440" alt="screen shot 2017-06-24 at 4 18 38 pm" src="https://user-images.githubusercontent.com/4109522/27511698-d122ee10-58f8-11e7-83ba-6d1a44720870.png">
