### ISSUE TITLE
2.0 Validation stops after the first invalid field

### ISSUE THREAD

**Issue by H3dz** [PolymerElements/iron-form#198]
Commit 60aa30218cc8c54009734628391bc826005d1b52 changed the validate function and now returns false as soon as there's one invalid element.

The problem with this is that now only the first invalid field is marked as invalid.
Before this commit all the the invalid fields were marked as invalid.

If this was done on purpose maybe a validateAll option should be added to iron-form.

**Comment by notwaldorf** [comment]
Oooops, you're totally right. That was my bad. Fixed in f1f9e92
