### ISSUE TITLE
[2.0-preview] Content type documentation mismatch

### ISSUE THREAD

**Issue by fwielstra** [PolymerElements/iron-form#199]
### Description

The `form` element inside an `<iron-form>` ignores the `content-type` attribute (As described in the [API documentation](https://www.webcomponents.org/element/PolymerElements/iron-form/elements/iron-form), but using the undocumented attribute `enctype` does work, as shown in the [basic.html test case](https://github.com/PolymerElements/iron-form/blob/2.0-preview/test/basic.html#L221).

### Expected outcome

A form is posted to the API using `Content-Type: application/json` and JSON serialized form contents when setting `content-type="application/json"` in the form

### Actual outcome

The form data is submitted as `text/plain`, with the POST body encoded as `[object Object]`.

### Steps to reproduce

```html
<!-- does not work -->
<iron-form>
  <form method="post" action="/api" content-type="application/json">
    <input type="text" name="name" value="Batman">
  </form>
</iron-form>

<!-- does work -->
<iron-form>
  <form method="post" action="/api" enctype="application/json">
    <input type="text" name="name" value="Batman">
  </form>
</iron-form>
```

### Browsers Affected
(only checked Chrome)
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
I think you're looking at the docs for 1.0, and expecting them to work in 2.0. If you look at the actual 2.0 docs, https://github.com/PolymerElements/iron-form/blob/2.0-preview/iron-form.html, there's no `content-type` attribute documented.
