### ISSUE TITLE
iron-form-response and iron-form-error does not have same object type in e.detail

### ISSUE THREAD

**Issue by peterlauri** [PolymerElements/iron-form#201]
### Description

Based on the documentation the events **iron-form-response** and **iron-form-error** should include IronRequestElement as e.detail. However, the differ in what is returned. 

```javascript
      /**
       * Fired after the form is submitted and a response is received. An
       * IronRequestElement is included as the event.detail object.
       *
       * @event iron-form-response
      */

      /**
       * Fired after the form is submitted and an error is received. An
       * IronRequestElement is included as the event.detail object.
       *
       * @event iron-form-error
      */

```

### Expected outcome

If I add event listener for the two events, I expect that e.detail to contain same type of object.

### Actual outcome

**With iron-form-error:**

![image](https://user-images.githubusercontent.com/3514945/27576103-39f46f52-5b1c-11e7-9ef5-e3593a5ff6ee.png)

Here e.detail.xhr is **undefined**.

**With iron-form-response:**

![image](https://user-images.githubusercontent.com/3514945/27576148-5ebb9cc0-5b1c-11e7-8663-8b000ae27dad.png)

Here I **can** access e.detail.xhr

**Comment by notwaldorf** [comment]
I think this is a problem with `iron-ajax`, not `iron-form`. We just use whatever events that element exposes. /cc @e111077 who's looked at `iron-ajax` last (and maybe he knows)

**Comment by e111077** [comment]
This is expected behavior from `iron-ajax`. Either the documentation in `iron-form` should be changed or `iron-form-error` should fire with `event.detail.request`

**Comment by peterlauri** [comment]
@notwaldorf do you want me to create a PR for this?

**Comment by peterlauri** [comment]
Created PR #206 to reflect what iron-ajax event.detail contains.
