### ISSUE TITLE
paper-button and iron-form, not working properly together.

### ISSUE THREAD

**Issue by vdegenne** [PolymerElements/iron-form#207]
When Using a `paper-button` element in an `iron-form`, pressing ENTER will not trigger the default behavior of a form input element, and won't submit the form.

### Steps to reproduce

1. create a basic iron-form example
2. use a `paper-button` into the form
3. focus in the `paper-button` element, type something.
4. press ENTER

**Comment by notwaldorf** [comment]
That is correct. This is not possible, since the `<form>` element only tracks native elements, like `<input>` and `<button>`. You need to call `yourIronForm.submit()` in your `paper-button`'s click handler if you want to use it in the form.
