### ISSUE TITLE
form POST request fails with unspecified form enctype

### ISSUE THREAD

**Issue by ianjosephwilson** [PolymerElements/iron-form#210]
### Description

The iron-form element does not submit a POST request as expected when no enctype is specified.

### Expected outcome

I would expect the enctype to default to "application/x-www-form-urlencoded" when no enctype is specified or behave the same way.  Or the necessity of enctype to be set for iron-ajax to function.

### Actual outcome

The body of the request appears to be the string "[object Object]" and the request fails because there is nothing for the server to receive.  I believe this is because the content-type of iron-ajax is set to null but the data is not a special data structure like FormData but instead is just a plain javascript object.

### Live Demo
https://jsbin.com/pidarav/8/edit?html,output

### Steps to reproduce

Put iron-form around a form with a text input and submit button on a page.
Don't specify the form's enctype but set the form's method to POST.
Open page in browser.
Submit form.

### Workaround

Set `enctype` to the expected default "application/x-www-form-urlencoded" when submitting POST requests.

### Browsers Affected

- [x] Chrome (Chromium Version 59.0.3071.104 (Developer Build) (64-bit))
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by ergo** [comment]
Confirmed, happens also on Firefox. Out of the box `iron-form` is broken and will not send correct POST requests at all.

**Comment by arthurevans** [comment]
Sounds like a result of the transition from an `is=` element to a wrapper.

**Comment by web-padawan** [comment]
Just took a quick look and it seems that [this line](https://github.com/PolymerElements/iron-form/blob/master/iron-form.html#L258) should be modified to fallback to `application/x-www-form-urlencoded`, since the method is already defined in the line above.

BTW this should be covered by tests, maybe a mock endpoint checking for `[Object object]` request body?

**Comment by ergo** [comment]
Fixed in https://github.com/PolymerElements/iron-form/pull/213

**Comment by ergo** [comment]
Any news on merging the PR? Right now iron-form is broken for all users for a month.

**Comment by ergo** [comment]
@notwaldorf Any chance new version of iron-form gets released soon?

**Comment by notwaldorf** [comment]
2.0.1 is already released, and should have this fix in, no?
