### ISSUE TITLE
.reset() method does not reset values loaded by ajax

### ISSUE THREAD

**Issue by maria-le** [PolymerElements/iron-form#219]
[See this SO question for more details.](https://stackoverflow.com/q/46697042/1640892)

> Edit 2
> This protected method `_init()` sets a protected property called `_defaults`. If I could access either the protected method or protected property, then I could call the method or set the property after `<iron-ajax>` returns its initial values.

**Comment by maria-le** [comment]
[Solution](https://stackoverflow.com/a/46712711/1640892)

**Comment by MitulGedeeya** [comment]
@maria-le 
Hi, what if I don't have iron-ajax?

I just wanted to save data on the server using firestore js and then want to reset iron-form.

can I reset form?
