### ISSUE TITLE
_validate() should be a public API

### ISSUE THREAD

**Issue by hawkett** [PolymerElements/iron-form#22]
I have situations where I want to validate the form without calling ```submit()```. I'm guessing others also have this requirement, and like me are calling ```_validate()``` to achieve this, so this shouldn't technically be a breaking change, but it probably will be.

**Comment by notwaldorf** [comment]
I think that's a good idea! I don't think it would be a breaking change, since it's a private method and you shouldn't be calling it in the first place :)

/cc @cdata @morethanreal to confirm, though
