### ISSUE TITLE
JSON deep object is malformed

### ISSUE THREAD

**Issue by PPCM** [PolymerElements/iron-form#225]
### Description

For the following iron-form, a deep json object is expected

```
<iron-form content-type="json">
   <input type="text" name="test.key1" value="value1">
   <input type="text" name="test.key2" value="value2">
</iron-form>
```
I tryed too with (as recommanded by W3C)
```
<iron-form content-type="json">
   <input type="text" name="test[key1]" value="value1">
   <input type="text" name="test[key2]" value="value2">
</iron-form>
```
An analyze of the name of elements should be done to build a JSON object as deep as needed

### Expected outcome

I expect the following JSON
```
{
   "test": {
                "key1": "value1",
                "key2": "value2"
              }
}
```

### Actual outcome

But the following output is given
```
{
   "test.key1": "value1",
   "test.key2": "value2"
}
```
or
```
{
   "test[key1]": "value1",
   "test[key2]": "value2"
}
```

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [X] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
I don't think this is supported, and this is definitely not supported by the native form either.  Whatever you pass as the name is a literal string key, not an object. 

Here's an example using the native form: http://jsbin.com/jucihu/edit?html,output. You can see that `test.one` is the submitted name.
