### ISSUE TITLE
Nested custom inputs not included in validation

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-form#232]
In 1.x, iron-form was able to include nested custom inputs during validation, that's because custom inputs would implement IronFormElementBehavior and fire register events.
This is not handled anymore in 2.x, hence these inputs are missed during validation, e.g.

```html
<iron-form id="form">
  <form action="/get" method="get">
    <paper-input-wrapper></paper-input-wrapper>
  </form>
</iron-form>

<dom-module id="paper-input-wrapper">
  <template>
    <paper-input name="check_wrapped" pattern="aa" value="b"></paper-input>
  </template>
</dom-module>

<script>
  addEventListener('WebComponentsReady', function() {

    Polymer({is: 'paper-input-wrapper'});

    // Wait one tick for observeNodes.
    Polymer.Base.async(function() {
      console.log('form.validate() should be false, but instead is ',
                  form.validate());
    });

  });
</script>
```

**Comment by valdrinkoshi** [comment]
A workaround I found is to expect custom elements that include custom inputs to implement a `validate()` method, since that's the method invoked by `iron-form` during validation (see [`validatable.validate` check](https://github.com/PolymerElements/iron-form/blob/master/iron-form.html#L216)).
```js
Polymer({
  is: 'paper-input-wrapper',
  validate: () => this.$$('paper-input').validate()
});
```
If that's the recommended way, we should mention this in the README.md
@notwaldorf WDYT?

**Comment by notwaldorf** [comment]
I would agree that the recommended way is for custom inputs to implement a validate (and a `name`/`value` attribute. Otherwise we'd have to arbitrarily pierce all shadow roots to go digging, and i don't think that works. WDYT?

**Comment by valdrinkoshi** [comment]
Makes sense, then it's worth mentioning in the README.md that iron-form handles custom or native inputs that are validatable (aka implement a `.validate()` method) and submittable (aka have a `name/value` attribute), and these inputs must be in the light dom.
