### ISSUE TITLE
2.1.0 regression: the slotted custom element is getting serialized twice

### ISSUE THREAD

**Issue by web-padawan** [PolymerElements/iron-form#235]
### Description
The element is first serialized as a distributed note into slot and then once again by direct node check.
 
### Live Demo
https://jsbin.com/voyixeveco/1/edit?html,console,output

### Expected outcome
The `serializeForm` call should return `{ foo: 'on' }` for the example above.

### Actual outcome
The `serializeForm` call returns `{ foo: [ 'on', 'on'] }` for the example above (see the console)

It looks like the reason is the condition here: https://github.com/PolymerElements/iron-form/blob/master/iron-form.html#L428

There probably should be an additional check to prevent serialization of the same node twice.

**Comment by moderndeveloperllc** [comment]
@web-padawan Thanks for finding the issue. I thought I was going a bit nuts when this started happening. Hopefully it will get fixed soon.

**Comment by notwaldorf** [comment]
(sorry about that folks; if anyone else has a fix it would be much appreciated 🙏 )

**Comment by TimvdLippe** [comment]
I have some time tomorrow morning to investigate.

**Comment by TimvdLippe** [comment]
Hm, this is actually a problem with the incorrect usage of this element. If you wrap the input with a `<form>` (per the update of `<iron-form>` 2.0 and the lack of `is=`), it is working as intended: https://jsbin.com/niribakicu/edit?html,console,output

@notwaldorf Not sure if we should support the case of not having a `<form>` in an `<iron-form>`?

**Comment by web-padawan** [comment]
Thanks @TimvdLippe . Shame on me, really forgot about that 😞  
Feel free to close as WAI. But personally, I would expect some kind of warning, though.

**Comment by TimvdLippe** [comment]
@web-padawan Absolutely no shame intended!! It is easy to forgot the form and I think a fail-fast approach in for example the `connectedCallback` of `<iron-form>` would work. We have to see whether we want to ship this as an error or a warning, as users might automatically update to the latest version. That could potentially break the whole application if we throw an error there. I think I would be in favor of a clear warning if the form is missing.

**Comment by adrysn** [comment]
If a submittable element is wrapped in a custom element with slot (e.g. `paper-material`), it still seems to be serialized twice even in the presence of `iron-form` and `form`:
https://jsbin.com/tanudop/edit?html,console,output

I am not sure this is intended or not, but there seems to be no reason not to use custom elements with slot inside a form.

**Comment by web-padawan** [comment]
@adrysn you're right, this is a valid use case for us as well.

**Comment by TimvdLippe** [comment]
Yes that looks broken and I think I understand why. Fixing it is a bit tough, but I will try to make something happen.

**Comment by TimvdLippe** [comment]
Non-ideal solution up at #239, but I was not able to figure out how to solve it otherwise :cry:
