### ISSUE TITLE
`content-type` property not available in 2.x

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-form#237]
The `contentType` property was available in 1.x and was a handy shortcut to set `form.request.contentType`, and its value would matter only on submit.
In 2.x, `request` is lazily instantiated, making it impossible for the user to access `form.request` before the submit is performed.

`iron-form 2.x` sets the `request.contentType` according to the `enctype` on the `<form>`, but the acceptable `enctype` values  do not include `application/json` https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/enctype, which is instead handled by `iron-request`.

Should we expose the `contentType` property also in 2.x, or should we suggest users to use `enctype` attribute on the `<form>` instead? 

The latter works, but since `application/json` is not a valid value, you'd get incongruent values for `form.encoding` http://jsbin.com/hajocam/1/edit?html,output

(my vote is still for the latter, and update the README.md accordingly)

**Comment by valdrinkoshi** [comment]
On the same note, the `headers` property was removed in 2.x, and because of the lazy instantiation of `this.request`, users cannot update the request headers in time.
I think the easiest would be to remove the lazy instantiation and immediately create the `iron-request`.

**Comment by notwaldorf** [comment]
Hmm the spec seems to suggest `enctype=application/json` should be ok:https://www.w3.org/TR/html-json-forms/

Agreed we should add it to the readme, but you could also access `form.request` in the presubmit event, right?

**Comment by valdrinkoshi** [comment]
oh nice, didn't see that `application/json` is a good value...wonder why is not mentioned in  https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/enctype

That's true, users can access to `form.request` on presubmit event 👌

**Comment by notwaldorf** [comment]
(fyi, not at all opposed to initiating `this.request` early)
