### ISSUE TITLE
[2.x] iron-validator-behavior elements included in validation

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-form#245]
Elements implementing `iron-validator-behavior` are considered as validatable elements because they implement the `validate()` method. The method signature is different, as it expects `value` to be passed as input.
As a result, `iron-form` will consider the form invalid because of such elements, e.g.
```html
<iron-form id="form">
  <form>
    <ssn-validator id="validator"></ssn-validator>
    <paper-input validator="ssn-validator" value="123-45-6789"></paper-input>
  </form>
</iron-form>
<script>
  console.log(form.validate()); // should be true
</script>
```
`form.validate()` method returns false because `iron-form` invokes `validator.validate()` without passing `value` as input.

This can be avoided by moving the `<ssn-validator>` outside the `<iron-form>`, but that's not an ideal solution.

**Comment by notwaldorf** [comment]
The validator shouldn't be inside of the form - you are not trying to submit the validator itself, and `paper-input` knows how to find it. Anything that's _inside_ of the form is basically fair game for being submitted.
