### ISSUE TITLE
paper-dropdown-menu does not get reset

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-form#252]
In 2.x, `paper-dropdown-menu` does not get reset, see demo page:
https://www.webcomponents.org/element/PolymerElements/iron-form/v2.0.0/demo/demo/index.html

This was working in 1.x, see demo page:
https://www.webcomponents.org/element/PolymerElements/iron-form/v1.1.6/demo/demo/index.html

**Comment by notwaldorf** [comment]
The problem seems to be that `_saveInitialValues` is called before `paper-dropdown-menu` distributes its `paper-listbox`, so it doesn't really have a default value when the form is looking for it :(

**Comment by notwaldorf** [comment]
`paper-dropdown-menu` doesn't seem to care about getting a `value` set on it (so `someDropdown.value = foo`, so I'm not sure what `iron-form` can do here (adding custom logic in sounds a bit gross)

**Comment by notwaldorf** [comment]
This issue was moved to PolymerElements/paper-dropdown-menu#281
