### ISSUE TITLE
Align reset with validate

### ISSUE THREAD

**Issue by 200Puls** [PolymerElements/iron-form#257]
### Description
When validate is executed the name of the elements is ignored. So even elements without a name are validated and marked invalid.

When reset is called after a validate only those elements which have a name set are reset back to a valid state.

### Expected outcome
This should be handled in a consistent way so that validate, reset and _saveInitialValues use _getValidatableElements and ignore the name. This would ensure that these methods all affect the same elements.

### Live Demo
https://jsbin.com/linetarexa/1/edit?html,console,output

### Steps to reproduce

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
This looks consistent with the native form too: http://jsbin.com/sorohes/edit?html,output
