### ISSUE TITLE
Why is iron-ajax created on the spot? I can no longer listen to iron-form's iron-ajax

### ISSUE THREAD

**Issue by shipagency** [PolymerElements/iron-form#258]
At some point in the last year the element has changed a little. One of the changes was to make the `request` property (which points to the iron-ajax element) only created when `_makeAjaxRequest()` is called.

We use `hot-network` which acts as a decorator, listening for events from iron-form's iron-ajax element.

But.. since the element isn't there till the very last microsecond before making the call... we can't listen to it.

On this basis, would you accept a PR where the IRON-AJAX is there from the moment the element's created?

Thanks!

**Comment by notwaldorf** [comment]
I think @valdrinkoshi had also looked at this; Valdrin, do you remember why we didn't merge it? Did we just punt on the PR? If so, @shipagency I think your PR sounds great!

**Comment by valdrinkoshi** [comment]
I noticed that in 2.x we don't expose the `request` property (#226), but I don't know why this was removed in the first place.
The removal was done during the port to 2.0 (https://github.com/PolymerElements/iron-form/pull/154), maybe the reviewers remember why it was removed (@e111077, @frankiefu) ?

**Comment by notwaldorf** [comment]
I think I was just trying to be optimal, tbh, and not for any other particular reason

**Comment by shipagency** [comment]
I really think it's important to allow other elements to tap into the `request` property -- especially since that's effectively the only way for a UI widget to know what's going on with the form ajax-wise.
We considered for example listening to `iron-form-response` and `iron-form-error` but... one very important one is indeed `request` (to grey out the UI). 

I am really puzzled though... The last version of the code with the creation of `request` in `ready()` was:

https://github.com/PolymerElements/iron-form/blob/b74e1cc101069910acfc74f0eff809965e305629/iron-form.html

The version STRAIGHT after that:

https://github.com/PolymerElements/iron-form/blob/1a7c1ebda65e7c63121a583ef8c3f48cc7c6b7f5/iron-form.html

And yet the commit is simply "rename ajax to request" (25th of May 2017) -- which DOESN'T seem to have a changeset that affects the ready() call (?!?)

![image](https://user-images.githubusercontent.com/36870314/37377498-448066a4-2765-11e8-9489-4363e7a79e67.png)

Two questions:

* Are you happy for me to make up a PR to put that back in ready() and documentation?
* Where is the commit that actually made the change? OK, not crucial but it is driving me bananas...

Right now we "fixed" it with this:

    var ironForm = document.createElement('iron-form')
    var proto = Object.getPrototypeOf(ironForm)
    var orig = proto.attached
    proto.attached = function () {
      if (!this.request) {
        this.request = document.createElement('iron-ajax')
        this.request.addEventListener('response', this._handleFormResponse.bind(this))
        this.request.addEventListener('error', this._handleFormError.bind(this))
      }
      orig.call(this)
    }

Not exactly award-winning code...!

**Comment by shipagency** [comment]
I changed completely the way my decorator works, and am no longer look for `request`. Since this is a case that is as edgy as they come (I think I would be the only user ever wanting this, and in fact i don't even want it anymore), I am closing this. Thanks for answering!

**Comment by notwaldorf** [comment]
Alright, cool. Then I'm gonna punt on this until someone else needs it in the future, since I don't really have the bandwidth to look into it to begin with 😅
