### ISSUE TITLE
Update validate() docs to state that only named form elements will be validated, or change validation behaviour to include un-named elements.

### ISSUE THREAD

**Issue by hawkett** [PolymerElements/iron-form#28]
https://github.com/PolymerElements/iron-form/pull/20 introduced a breaking change in validation behaviour such that only named elements are validated. The break occurred for anyone that was relying on validation for un-named form elements.

At that time, one reason given was an inability to serialise un-named form elements. Given that #22 decoupled validation from form submission/serialisation, should we still have the constraint that only named form elements will be validated? Validation isn't dependent on the ```name``` attribute, so it seems an unnecessary constraint for the validation phase.

If this constraint is to be retained, can the validate() documentation be updated to explicitly call this out?

Thanks!

**Comment by notwaldorf** [comment]
@hawkett Hmm, interesting. The reason why I made that change (and thought the previous behaviour was incorrect), is because un-named elements can't be submitted in the form (can't serialize them without a name), so it doesn't really make sense to validate them (if it can't be submitted in the form, it shouldn't really block form submission).

I definitely agree that I should add the comment, but does the explanation above make sense?

**Comment by hawkett** [comment]
hmm... I'm not convinced that all validatable form elements should be expected to be submitted in this way. Some examples:

* A passwordVerification (i.e. entering your password twice) field may not be submitted.
* Many people don't use the form's submit capability to actually submit the form at all - they may just gather the data from the form and submit json via XHR. In that case form element names are not required.
* Client-side only forms, or forms that are intended for submission via another means such as WebSocket simply won't (or can't) use the form's submit capability.

In general it seems tightly coupling validation behaviour to submission behaviour isn't the right way to go - they're really two independent form capabilities.

That said, I can see it being good practice to name form elements, and I guess since polymer is opinionated it may choose to enforce that - but in that case it should be explicitly that, and not related to submission mechanics, perhaps... :)

**Comment by notwaldorf** [comment]
Ok, did some reading of the [spec](http://www.w3.org/TR/html401/interact/forms.html#successful-controls) and if I understand correctly that section and the one after on form submission, when you submit a form, only the controls that have a name-value pair are considered ("A successful control must be defined within a FORM element and must have a control name.").

When it comes to validation (another [spec](http://www.w3.org/TR/html5/forms.html#barred-from-constraint-validation), all submittable elements are candidates for validation if the element has the `required` attribute (see http://www.w3.org/TR/html5/forms.html#attr-input-required). (which I believe the `iron-form` code should respect, and if it doesn't, that's a bug)

This is true of native forms too: (jsbin is down, here is a jsfiddle): https://jsfiddle.net/7p3n4yyg/
The second input is required, and the form will not submit until it has valid input.

ll; dr: if you don't want a form element to be validated, it shouldn't be required.

**Comment by hawkett** [comment]
Interesting. I'm reading the spec. bits you quoted to mean that:

a) Submittable elements have a name
b) Only 'submittable elements' will be validated

The first point seems reasonable, but the second point seems a bit loosely defined. From my reading of the [definition of submittable elements](http://www.w3.org/TR/html5/forms.html#category-submit), it is, in a generic sense, a submittable element whether it has a name or not (e.g. an ```input``` element is defined as submittable, regardless of whether it has a name). In a particular instance where such a submittable element has no name, its value won't form part of the submitted data.

That may seem to be splitting hairs, but there's a couple of things to consider:
a) The jsfiddle you linked performs validation, but the element has no name. Same behavior on chrome/firefox.
b) Spec. joy aside, it seems generally much more useful to validate where possible and not couple to form submission mechanics - the two examples I gave earlier are realistic and common cases where form submission isn't wanted but validation is.

That said, if polymer wants to make name a requirement for validation, it's not a huge burden on the developer (and may even be good practice) as long as that's clearly documented. My 2c would simply be that it doesn't seem necessary, and also doesn't match current browser implementations of validation.

**Comment by notwaldorf** [comment]
@hawkett after some deliberation, i think i will have `iron-form` match the browser behaviour, and validate regardless of a `name` attribute. Is that ok with you? (slash, will it cause you extra problems again?) :(

**Comment by hawkett** [comment]
@notwaldorf - thanks for the update - that sounds great!
