### ISSUE TITLE
HTML Form submit event not being triggered

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/iron-form#32]
_From @tjsavage on July 21, 2015 20:37_

_From @steelbrain on July 21, 2015 1:3_

Consider you have the following markup
```html
<form id="form" action="javascript:" method="post">
  <input type="text" name="username" />
</form>
<script>
var form = document.getElementById("form")
form.on('submit', function(e){
  e.preventDefault()
  console.log("Hey")
})
</script>
```
now if you focus the input element and press enter, the submit event won't be triggered.
Now if you add `<button>Something</button>` without the form bounds, pressing enter after focusing the event or clicking the button, both would work.
Now if you replace that button with a paper-button `<paper-button raised>Hey</paper-button>`, submit will be impossible again because there's no `button` in the form.
Now if you add `is="iron-form"` to the tag, and the form will be submitted by the paper-button now but it won't trigger the native `submit` event, not even the `iron-form-submit` event.

I am using Google Chrome 43.0.2357.134

_Copied from original issue: Polymer/polymer#2128_

_Copied from original issue: PolymerElements/paper-button#34_

**Comment by tjsavage** [comment]
_From @steelbrain on July 21, 2015 1:10_

Maybe this can be solved by making `paper-button` extend the `button` tag?

**Comment by tjsavage** [comment]
Hm... Seems to me like an issue with `iron-form` - will move there.

**Comment by tjsavage** [comment]
Moving again, correctly this time.

**Comment by MichaelXavier** [comment]
Bumping this issue. Does anyone know why this happens?

**Comment by steelbrain** [comment]
@MichaelXavier I think I've explained the cause and a workaround in the first post.

**Comment by MichaelXavier** [comment]
@steelbrain ah thanks. This may be obvious but I've found that visibility of the `<button>` tag does not seem to affect your ability to submit the form. So if you want to use a `paper-button` tag *and* have enter submit, you can have an empty, hidden `<button></button>`.

**Comment by notwaldorf** [comment]
My understanding of forms is that you need at least an `<input type="submit">` or a `<button>` for the form to be automatically submittable. So you're right, a hidden `button` would do that trick.

I don't think adding this kind of logic to `paper-button` (to look up at its parent and see if it's a form) is worth it, since the `form` behaviour is already kind of weird, and the work around is fairly straight forward (as mentioned in this thread).

**Comment by steelbrain** [comment]
@notwaldorf I see, Thanks!
