### ISSUE TITLE
Calling submit() method of an iron-form inside paper-dialog also close the dialog

### ISSUE THREAD

**Issue by wiphoenix** [PolymerElements/iron-form#33]
_doFakeSubmitForValidation in iron-form trigger _onCaptureClick in iron-overlay-behavior and cancel the overlay

**Comment by notwaldorf** [comment]
@wiphoenix I don't have a good solution for this right now (i'm looking into it, but forms are the worst) :(
In the meantime, you can set `disable-native-validation-ui` on your form, which will not call `_doFake...`.

**Comment by bicknellr** [comment]
@wiphoenix This seems to be fixed already: http://jsbin.com/fixawilido/1/edit?html,output. Can you still repro?

**Comment by notwaldorf** [comment]
Closing, as there seems to already be a fix, and this issue looks stale
