### ISSUE TITLE
Additional headers to the ajax request

### ISSUE THREAD

**Issue by andrewebdev** [PolymerElements/iron-form#34]
Certain backend frameworks, like Django, may have additional csrf protection included. For ajax post requests django expects a `X-CSRFToken` header. If this token is not passed the request will raise a 403.

In cases like this it would be nice if we could set additional headers for the ajax request, similar to how we can do this on the `iron-ajax` element.

**Comment by 7Ds7** [comment]
This would be great as of now the only way that i managed to change the iron-form headers is

``` element._requestBot.headers = {"X-CSRF-Token": "thetokenstring" } ```

**Comment by notwaldorf** [comment]
Already fixed by https://github.com/PolymerElements/iron-form/pull/35
