### ISSUE TITLE
Support for paper elements

### ISSUE THREAD

**Issue by eximius313** [PolymerElements/iron-form#39]
Please provide support for ```paper-radio-group```, ```paper-radio-button``` and ```paper-checkbox```.
Currently they are ignored in the request data.

**Comment by notwaldorf** [comment]
There's a bunch of PRs in flight to enable this (see https://github.com/PolymerElements/paper-checkbox/pull/40); hopefully they'll all land by the end of next week.

Sorry for the delay!

**Comment by notwaldorf** [comment]
These should all work now!
