### ISSUE TITLE
Safari-specific duplicate reading of custom elements' value

### ISSUE THREAD

**Issue by inureyes** [PolymerElements/iron-form#41]
* This is different issue from #12 : similar behavior but different reason.  
 * In safari, some custom elements are read three times.

```
      // Go through all of the registered custom components.
      for (var el, i = 0; el = this._customElements[i], i < this._customElements.length; i++) {
        if (this._useValue(el)) {
          addSerializedElement(el);
        }
      }

      // Also go through the form's native elements.
      for (var el, i = 0; el = this.elements[i], i < this.elements.length; i++) {
        // Checkboxes and radio buttons should only use their value if they're checked.
        // Also, custom elements that extend native elements (like an
        // `<input is="fancy-input">`) will appear in both lists. Since they
        // were already added as a custom element, they don't need
        // to be re-added.
        if (!this._useValue(el) ||
            (el.hasAttribute('is') && json[el.name])) {
          continue;
        }
        addSerializedElement(el);
      }
```

 * Example: paper-input
  * Intended behavior: iron-form reads paper-input and passing native elements logic
  * In Safari : in custom element reading code, ```iron-form``` reads ```paper-input``` and ```iron-input```. In form's native code read part, ```iron-form``` also reads ```input``` field, even they are same element (with inheritance) with same name.
  * ```addSerializedElement(el)``` stacks values if same element is already read. Therefore, generated json field looks like: ```"name":['value','value','value']```
 * Reason
  * In Safari, custom element has "is" attribute (can read as element.is) however existence of "is" attribute cannot be confirmed with ```hasAttribute``` method. ```hasAttribute('is')``` returns false.
  * element.is of native elements return ```false``` in Safari / ```undefined``` in Chrome.  
  * It could be webcomponents.js problem.

**Comment by notwaldorf** [comment]
@inureyes I ran the demo code in Safari, which has a `paper-input`, and the value is only submitted once. Do you still see this happening with latest versions of all the elements?

**Comment by inureyes** [comment]
@notwaldorf Now it's working without workaround. I think it is related to the problem between webcomponents.js and safari. Thanks.
