### ISSUE TITLE
Malformed form submission

### ISSUE THREAD

**Issue by veerkat** [PolymerElements/iron-form#42]
When i use this element for my app. Submit form to server, the server get the form like this: 

    [object Object]

, it is a string. is it a bug?

**Comment by notwaldorf** [comment]
Do you have more details? Is this happening with the latest versions? Are you using post or get? What are you actually submitting?

**Comment by veerkat** [comment]
thank for your reply。 when i upgrade iron-from to latest version, it works well. It should happen with the old versions.
