### ISSUE TITLE
Feature request: non type-extension <iron-form> element

### ISSUE THREAD

**Issue by notwaldorf** [PolymerElements/iron-form#46]
To get around the problem of redirecting to the `action` url, we can create a custom `<iron-form>` element that would
- have a child native `form` to track the native `inputs` (like now)
- still listen to `IronFormElementBehaviour` children to track custom elements (like now)
- on submit, either 
  
  a) use the current strategy and `iron-ajax` its way out or
  b) make hidden inputs that mirror all the name/values of the custom elements, add them to the child for form, and do `form.submit()` and let the child form take care of it

The best behaviour is that you don't _need_ b), then you should use `<form is="iron-form">`, otherwise use this new, custom, element.

:sparkles:

**Comment by robdodson** [comment]
yay! For folks building a traditional web page this could be a huge win

**Comment by kito99** [comment]
+1 for this. Even supporting a redirect as a result of the Ajax request would be very helpful.

**Comment by jab** [comment]
I believe PolymerElements/paper-button#69 would complement this well IIUC.

**Comment by notwaldorf** [comment]
Updates: I am totally making progress on this, and should have something to show around soon!

**Comment by robdodson** [comment]
@notwaldorf AWESOOOOOOOME

**Comment by jab** [comment]
where's a "cheering!" emoji when you need one!

**Comment by notwaldorf** [comment]
Lower those expectations, friends. It will probably be filled with bugs. I will try to finish it and send it out for review over the weekend :)

**Comment by notwaldorf** [comment]
This is basically the 2.0+ iron-form, so this can be closed
