### ISSUE TITLE
serialize() does not pick all paper elements

### ISSUE THREAD

**Issue by Akash-dvd** [PolymerElements/iron-form#49]
iron-form serialize method does not pick all paper elements like paper-radio-group ,paper-dropdown-menu. These elements don't have a name attribute but the core elements do have.

**Comment by notwaldorf** [comment]
`paper-radio-buttons` (and toggle buttons) should be fixed as of yesterday. 

It is true that `paper-dropdown-menu` doesn't -- I've opened https://github.com/PolymerElements/paper-dropdown-menu/issues/32 for that (since the issue is with the elements themselves, and not the form)
