### ISSUE TITLE
CORS error is treated as a correct response

### ISSUE THREAD

**Issue by AitorGuerrero** [PolymerElements/iron-form#51]
At iron-request:succedeed (line 149), tells that status 0 is treated as a "succeed" because is the status received in a file:// protocol.
The problem is that when there is a CORS problem, the browser (at least Chrome), uses the same state. And it seems that there is no other way to differentiate between them.
I think that is more important (and secure) to understand 0 state as an unexpected result, so, an error, than as an success.
In my case, the user thought he saved an entity, and continued working.

**Comment by gertcuykens** [comment]
suggesting to make the status attribute available `e.target.status == 200` i need something similar to determine which error i get 401 500 ...

**Comment by notwaldorf** [comment]
@rictic I think this is an iron-ajax question; would you mind taking a look, please?

**Comment by rictic** [comment]
This should be fixed as of iron-ajax v1.0.6 by https://github.com/PolymerElements/iron-ajax/pull/126

If this is till an issue, let us know.
