### ISSUE TITLE
Support for PUT, PATCH and DELETE

### ISSUE THREAD

**Issue by gmercey** [PolymerElements/iron-form#6]
Hi,

I tried to use PUT, PATCH and DELETE with the element, but it automatically fallback to GET. After some tests, I find out that it wasn't the element that was doing that, but something else (polymer ?).

Is there any plan to implement those methods into polymer ?

Thank you

**Comment by notwaldorf** [comment]
According to the spec, HTML forms only support GET and POST (http://www.w3.org/html/wg/drafts/html/master/semantics.html#attr-fs-method). <iron-form> is just an extension of a normal HTML form, so it won't work with PUT/PATCH/DELETE either (those only work for HTTP requests)

Also see: http://stackoverflow.com/questions/8054165/using-put-method-in-html-form/8054444#8054444

**Comment by rnicholus** [comment]
@gmercey If you are looking for PUT/PATCH support, [take a look at `<form is="ajax-form">`](https://github.com/rnicholus/ajax-form).
