### ISSUE TITLE
Support posting structured json data

### ISSUE THREAD

**Issue by srikkbhat** [PolymerElements/iron-form#63]
Currently form data is serialized into a flat structure. Would be great if it serializes into structured data as below.

Current:
{
  'user.name': 'abc',
  'user.address.street': '123 abc',
  'user.address.city': 'xyz'
}

Expected:
'user': {
  'name': 'abc',
  'address': {
    'street': '123 abc',
    'city': 'xyz'
  }
}

**Comment by nverba** [comment]
This would be a handy feature...

**Comment by notwaldorf** [comment]
I will be sending a PR for https://github.com/PolymerElements/iron-form/issues/26 soon, which will let you hook into the form pre-submission, and you can manually change what's being submitted to the server.

**Comment by srikkbhat** [comment]
Great! Thanks for the update.

**Comment by notwaldorf** [comment]
Fixed with #67
