### ISSUE TITLE
Mobile A11y Testing 11/1

### ISSUE THREAD

**Issue by lpalmaro** [PolymerElements/iron-form#74]
On Android with Talkback:
1) in the part of the UI with the radio buttons, there seems to be one extra linear swipe needed to get from checkbox > red > next checkbox. Instead it is one swipe to get to the checkbox, one to get to the color name (e.g. red), then one swipe with nothing, then another swipe to get to the next checkbox on the line below. Not a huge deal, just odd. 

2) The Browsers drop down list doesn't notify me that it's also a text entry field. As I start typing in this field, e.g. IN, then internet explorer shows up as a suggested item. However, I have no way to swipe to this easily unless I use touch exploration. We need to think through a better way to not only notify the user that an autosuggestion is showing, but then give him/her easy access to it. "

**Comment by notwaldorf** [comment]
The browsers drop down is a native `input` with a `datalist`, so we can't really control its behaviour.
The radio buttons are also native radio buttons, so I think that's just how they behave on mobile, maybe? 

Closing this, as these seem like issues with the native elements
