### ISSUE TITLE
API docs should clarify handling of form data

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/iron-form#75]
Currently, we hand `contentType` off to `iron-ajax`, which slips it under the hood to `iron-request`, which may or may not do magic stuff to the form data.

To make this super clear, we should mention  how `contentType` is used.

Even though a) `method` is a native property of the form element, and b) we show it in the head docs, I think it would be nice to include it in the API reference if possible. Or _if not_, at least mention that it's a standard part of the `<form>` API so people don't go digging through the API doc scratching their heads.

Related: https://github.com/PolymerElements/iron-ajax/issues/139

**Comment by notwaldorf** [comment]
@arthurevans I will add a note about iron-ajax's `contentType`. I'm not sure what we should do about `method` though. In no other element do we document native attributes (and iron-form is just a type extension). I would kind of assume that if you're using it, you're expecting it to work like `<form>` does, but I will add a not linking to the HTML spec, perhaps.
