### ISSUE TITLE
facilitate common ajax form submit behaviors

### ISSUE THREAD

**Issue by jab** [PolymerElements/iron-form#77]
For ajax forms — which don't cause full page reloads when submitted (and therefore don't benefit from the browser's visual feedback that something is happening, but rather just stay in place) — a common UI pattern is to disable the submit button (to prevent double submits) if there is one, and to give additional visual feedback that something is happening (e.g. show a spinner, change the submit button's label from "submit" to "loading...", etc.).

A [PR](https://github.com/PolymerElements/iron-form/pull/73) I worked up for #68 indicated that this currently involves writing boilerplate like:
```javascript
    function toggleLoading(event) {
      var button = document.getElementById('submitButton');
      var spinner = document.getElementById('spinner');
      button.toggleAttribute('disabled', this.request.loading);
      spinner.toggleAttribute('active', this.request.loading);
      spinner.toggleAttribute('hidden', !this.request.loading);
    }
```

Is there a generic way iron-form could facilitate this to reduce the need for boilerplate? For example, could iron-form accept options that would let it automatically toggle the appropriate attributes on the elements you indicate while the request is loading?

**Comment by notwaldorf** [comment]
I think that's making `iron-form` care about implementation details of a particular application, which isn't right. I think that if you want, in your application, to change the UI as a response to different states in a `<form>`, that totally makes sense. I think requiring a `<form>` to automagically modify parts of your application that are not in its control goes against the idea of element encapsulation.

I would suggest binding the `disabled` and `hidden` attributes to the form's `request.loading` attribute (you might need an intermediate computed property depending on what you need) if you want to reduce the boilerplate, but it's unlikely that we would add this to the form itself.
