### ISSUE TITLE
validate() doesn't validate extended native element

### ISSUE THREAD

**Issue by zboralski** [PolymerElements/iron-form#86]
`<input is="iron-input"...>` isn't registered as a custom elements and validate() assumes it has already been validated : 

>Custom elements that extend a native element will also appear in this list, but they've already been validated.

Sample code:

```js
    <profile-name-validator></profile-name-validator>
    <form is="iron-form" id="form" method="post" action="/form/handler"
      <input is="iron-input" name="name" required validator="profile-name-validator"></input>
  </form>
```

input's validate() works but it is never called by iron-form's validate()

```
$0 [input]
$0.validate()
false
$0.parentElement.validate()
true
```

I guess the solution for now is to write a custom element to wrap iron-input or just use a paper-input which works fine (but is a pain to restyle).

**Comment by zboralski** [comment]
As @metanov suggested on slack, adding IronFormElementBehavior to iron-input fixes the issue.

**Comment by MeTaNoV** [comment]
could you move this to `iron-input` and update related to the reason of the issue? :)

**Comment by zboralski** [comment]
@MeTaNoV done

https://github.com/PolymerElements/iron-input/issues/63
