### ISSUE TITLE
Should the red colour of a required field disappear, when it is filled?

### ISSUE THREAD

**Issue by LoveAndHappiness** [PolymerElements/iron-form#88]
Right now on the demo, when I click the submit button, everthing turns red. Expected behaviour.

But when I start filling out the fields, they don't turn automatically blue, once the requirements are met.

Is this expected behaviour?

**Comment by notwaldorf** [comment]
Only if the fields have some form of auto-validation (like `paper-input` does). Otherwise, you have to manually validate the fields yourself (this is the behaviour of native inputs, for example)
