### ISSUE TITLE
POST not sending body

### ISSUE THREAD

**Issue by jeffreyzant** [PolymerElements/iron-form#9]
By creating a POST form the method is send to the iron form in Lower Case, but it is being matched with a Upper Case 'POST'. 

This causes the element not to add the requestBody and only request params.

      console.log(this.method);          // shows 'post'
      if (this.method == 'POST') {
          console.log('passed');         // not passed
          this._requestBot.body = JSON.stringify(json);
      }

**Comment by stuartflanagan** [comment]
Native form element seems to force the method to lower case.

**Comment by ALiangLiang** [comment]
So It's not be fixed in the version 1.0.2?

**Comment by mcarey1590** [comment]
No it's not. You can get the fix here https://github.com/mcarey1590/iron-form. They should be merging this soon and will be in the next point release

**Comment by ALiangLiang** [comment]
Thanks. :D
It's perfectly fix the bug.

**Comment by notwaldorf** [comment]
This has been merged now, and version `1.0.3` should have the fix. Thanks for the patience :)
