### ISSUE TITLE
Add presubmit attribute for specifying JS function

### ISSUE THREAD

**Issue by indolering** [PolymerElements/iron-form#91]
Currently, if you want to modify a form before it's submitted you must declare a listener in a lifecycle attribute.  Ideally, one could just specify a JS function directly using an attribute.

In terms of syntax, you could support `presubmit` for regular JS functions and `pre-submit` for functions that belong to the Polymer element.  Edit: just to clarify, the `pre-submit` function should have the `this` attribute set to the Polymer element so I don't have to abuse `on-submit` to inject values into hidden form fields.

*P.S. What's the correct terminology for JS functions that are part of the Polymer element?*

**Comment by indolering** [comment]
Ideally, the form and/or request objects would be passed in as arguments to the `pre-submit` function.

**Comment by notwaldorf** [comment]
What do you mean by `lifecycle attribute`? You can just add a plain vanilla listener
```
document.getElementById('someForm').addEventListener('iron-form-presubmit', presubmit);
```
Where `presubmit` is a normal JavaScript method where `this` points to the thing that generated the event, so the form. Here is a jsbin as an example: http://jsbin.com/toyiye/edit?html

I don't think it's very common for Polymer elements to declare callbacks as an attribute, when events work (and unless I misunderstand, it seems to do what you want in this case)

**Comment by indolering** [comment]
Yes, but I have to inject the addEventListener in a lifecycle callback of the element (`ready`, `attached`, etc) which can be overwritten by a behavior and (eventually) a child element.  The `this` assignment is also inelegant.  These aren't deal-breakers, but it would be a nicer API.

**Comment by notwaldorf** [comment]
I think that's just the standard way of adding listeners, though. At some point in your element, if you want your element to respond to an event, you need to add a listener.

If I understand correctly, you want something like
```
<form is="iron-form" action="/" presubmit="foo">
```
Where `foo` is a JS function that does something before the form is submitted? If that's the case, I think that's fairly unusual for Polymer Elements, and it would stray away from our best practices a lot.

Here's a JsBin with an example of how this event is actually used: http://jsbin.com/yoriso/edit?html,console,output

You'll notice that the `this` is already bound correctly to the `form`, and you're not abusing the `on-submit` event. You're just submitting the form as you would normally do, and adding something to the request element in the presubmit.
