### ISSUE TITLE
Reset validation

### ISSUE THREAD

**Issue by slavko-ptitsyn** [PolymerElements/iron-form#93]
After `form.reset()` function call, input field is cleared, but validation message is still being displayed.
![main](https://cloud.githubusercontent.com/assets/16416029/11983532/c81f2d34-a9bc-11e5-8cae-90890fbcf3da.png)
Is it possible to add validation messages clearing to 'reset' function or add a separate function?

**Comment by notwaldorf** [comment]
@slavko-ptitsyn Yup, you're totally right! A line in here (https://github.com/PolymerElements/iron-form/blob/master/iron-form.html#L408) probably needs to be added to call `el.validate()` or something like that.
Let me know if you want to submit a PR for this, or if I should take a look!

**Comment by slavko-ptitsyn** [comment]
Take a look, please.

**Comment by slavko-ptitsyn** [comment]
@notwaldorf Can you create a new release with that fixes?

**Comment by notwaldorf** [comment]
Done!

**Comment by Roxy94** [comment]
This issue appears again in Polymer 2

**Comment by notwaldorf** [comment]
@Roxy94 -- form reset is not yet implemented for the 2.0 version of iron-form

**Comment by jhrdina** [comment]
Could you please reopen the issue?

**Comment by pdesjardins90** [comment]
I'd like to add that floating labels don't come down either upon reset (seems related)

**Comment by jhrdina** [comment]
Unfortunately, I couldn't reproduce the floating labels issue. Could you please try to create a small demo?

**Comment by Spyridox** [comment]
In Polymer 2 `reset` also doesn't reset char counters. Should I create a new issue for this?

**Comment by notwaldorf** [comment]
Closing, since this is a super old issue and resetting works v differently on Polymer 2/3
