### ISSUE TITLE
Problem with forms and input foucs on Android

### ISSUE THREAD

**Issue by zboralski** [PolymerElements/iron-form#96]
I tried using :

```html
<form on-submit="performSearch" class="search horizontal center-justified layout">
```

and 
```html
<form is="iron-form"  action="" on-submit="performSearch" class="search horizontal center-justified layout">
```

If I use e.preventDefault in the submit event or in the presubmit event, the Android keyboard won't hide itself.

I took a look at polymer-element-catalog's source to check how you guys do it and you use the first version (not the iron form) one... and your search field on Android 6.0 doesn't work at all. If you start typing in the the input field the search is performed and the keyboard doesn't lose focus.

**Comment by notwaldorf** [comment]
Eeek, this sounds like a bug. Thanks for reporting it, I'll take a look

(Let me know if you're interesting in investigating this and sending a PR to fix it, though!)

**Comment by zboralski** [comment]
@notwaldorf  I used a hack to work around the issue :

```js
    function hideKeyboard() {
      setTimeout(function() {
        var el = document.createElement('input');
        el.style.width = '1px';
        el.style.height = '1px';
        el.style.position = 'absolute';
        el.style.top = '-100px';
        document.body.appendChild(el);
        el.onfocus = function() {
          setTimeout(function() {
            el.setAttribute('style', 'display:none;');
            setTimeout(function() {
              document.body.removeChild(el);
              document.body.focus();
            }, 14);
          }, 200);
        };
        el.focus();
      }, 50);
    }
```

I have no idea how to fix this issue in a cleaner way...

**Comment by notwaldorf** [comment]
Looking at this again, I don't think I understand what you're trying to do. Can you please provide a small, reproducible JSBin that repros what you're trying to do? I tried a basic form (https://output.jsbin.com/hidimu) and the keyboard shows and hides as expected.

Please re-open this issue when you have some repro steps we can test! Thanks! :)
